name:  CI

on: push

jobs:
  system-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build executable
        run: go build -o moneyLeft.exe ./main.go

      - name: Run system tests
        run: go test -v ./...
